name: ditherorg
favicon: null
layout_spectrum: 0.6325090273749083
typography_spectrum: 0.75614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27709981333464384
  lightness: 0.20200623176060617
  saturation: 0.06141490978188813
  rhythmicContrast: 0.12222880078479648
purpose: []
