name: ditherorg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7f0ff'
    - '#080808'
    - '#94b2ce'
    - '#df8249'
    - '#67651a'
  brandStrength: 0.6875
  lightness: 0.20200623176060617
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
